sign_in = "xpath://div[@class='panel header']//a[normalize-space()='Sign In']"
email_locator = "id:email"
password_locator = "id:pass"
sign_in_button = "xpath://button[@class='action login primary']"
account_panel = "xpath://div[@class='panel header']//*[contains(text(),'Welcome')]"